export class Karyawan {
	id?: number;
  lokasi_tugas_id?:number;
  sub_bagian_id?:number;
	nip?: string;
  nama?: string;
	jenis_kelamin?: string;
	tempat_lahir?: string;
	tgl_lahir?: string;
  tgl_masuk?: string;
  tgl_keluar?: string;
  tgl_hbs_kontrak?: string;
	alamat?: string;
  agama?: string;
	foto?: string;
	status_id?: number;
  tipe_karyawan_id?: number;
  jabatan_id?: number;
  golongan_id?: number;
  departemen_id?: number;
  pangkat_id?: number;
  status_kawin?: string;
  golongan_darah?: string;
  status_pajak?: string;
  email?: string;
  telp?: string;
  no_hp?: string;
  no_ktp?: string;
  no_kk?: string;
  no_npwp?: string;
  no_bpjs?: string;
  no_bpjs_ks?: string;
  no_rek_bank?: string;
  nama_bank?: string;
	fcm_token?: string;
  username?:string;
  password?:string;
  is_admin?:boolean;
  role_id?:[];
  riwayat_jabatan?:[];
  riwayat_pangkat?:[];
  riwayat_keluarga?:[];
  riwayat_pendidikan?:[];
  riwayat_hukuman?:[];
  riwayat_penghargaan?:[];
  riwayat_bahasa?:[];
  riwayat_keahlian?:[];
  riwayat_pelatihan?:[];
  riwayat_pengalaman?:[];
  is_jht?: boolean;
  is_jp?: boolean;
  is_jks?: boolean;
  login?:any;
}
